algo = input('Digite algo:')
print('O tipo primitivo deste valor é ', type(algo))
print('Só tem espaços? ', algo.isspace())
print('É um numero? ', algo.isnumeric())
print('é uma palavra ou letra sem numeros? ', algo.isalpha())
print('é uma palavra com letras e/ou numeros? ', algo.isalnum())
print('Só tem letras maiusculas? ', algo.isupper())
print('Só tem letras minusculas? ', algo.islower())
print('Tem letras maiusculas e minusculas? ', algo.istitle()) 
